'use strict';

const SEED = [
  {
    "id": "PLT-01",
    "fecha_alta": "2026-06-17",
    "creador": "Equipo Eureqa3D",
    "area": "Visor 3D",
    "titulo": "Capas on/off, opacidad, cortes X/Y/Z, agrupacion por categoria + presets, suavizado, tumor en azul",
    "historia": "Como cirujano quiero encender/apagar estructuras y ajustar opacidad para entender la anatomia del caso",
    "tipo": "Feature",
    "modulo": "Visor (three.js)",
    "prioridad": null,
    "estimacion": null,
    "estado": "Hecho",
    "origen": "Interno",
    "responsable": "Kira Level (dev)",
    "fecha_cierre": "2026-06-17",
    "notas": null
  },
  {
    "id": "PLT-02",
    "fecha_alta": "2026-06-17",
    "creador": "Equipo Eureqa3D",
    "area": "Co-branding",
    "titulo": "Co-branding Kira Level + Eureqa3D, producto EureqaVisor3D",
    "historia": "Como empresa quiero una identidad de marca coherente en el producto",
    "tipo": "Mejora",
    "modulo": "Visor (UI)",
    "prioridad": null,
    "estimacion": null,
    "estado": "Hecho",
    "origen": "Interno",
    "responsable": "Kira Level (dev)",
    "fecha_cierre": "2026-06-17",
    "notas": null
  },
  {
    "id": "PLT-03",
    "fecha_alta": "2026-06-17",
    "creador": "Equipo Eureqa3D",
    "area": "TAC->3D",
    "titulo": "3 vias TAC->3D: mallas->glb, hueso por umbral, IA TotalSegmentator",
    "historia": "Como Eureqa3D quiero generar el modelo desde TAC por varias vias segun el caso",
    "tipo": "Feature",
    "modulo": "Pipeline + GPU (Modal)",
    "prioridad": null,
    "estimacion": null,
    "estado": "Hecho",
    "origen": "Interno",
    "responsable": "Kira Level (dev)",
    "fecha_cierre": "2026-06-17",
    "notas": null
  },
  {
    "id": "PLT-04",
    "fecha_alta": "2026-06-17",
    "creador": "Equipo Eureqa3D",
    "area": "Catalogo",
    "titulo": "Catalogo real: KiTS rinon+tumor, escena quirurgica, IA tronco, BodyParts3D, pulmon+tumor, TAC mano",
    "historia": "Como comercial quiero casos demo realistas para ensenar el producto",
    "tipo": "Feature",
    "modulo": "web/public/models",
    "prioridad": null,
    "estimacion": null,
    "estado": "Hecho",
    "origen": "Interno",
    "responsable": "Kira Level (dev)",
    "fecha_cierre": "2026-06-17",
    "notas": null
  },
  {
    "id": "PLT-05",
    "fecha_alta": "2026-06-17",
    "creador": "Equipo Eureqa3D",
    "area": "Uploader",
    "titulo": "Uploader (mallas / TAC) + persistencia (Railway Volume) + enlaces con caducidad 30 dias",
    "historia": "Como cirujano quiero subir un caso y obtener un enlace navegable sin instalar nada",
    "tipo": "Feature",
    "modulo": "Backend (FastAPI)",
    "prioridad": null,
    "estimacion": null,
    "estado": "Hecho",
    "origen": "Interno",
    "responsable": "Kira Level (dev)",
    "fecha_cierre": "2026-06-17",
    "notas": null
  },
  {
    "id": "PLT-06",
    "fecha_alta": "2026-06-17",
    "creador": "Equipo Eureqa3D",
    "area": "IA GPU",
    "titulo": "IA en GPU on-demand (Modal): subir TAC -> organos automaticos en ~1-2 min. Flujo completo",
    "historia": "Como Eureqa3D quiero segmentar organos automaticamente con coste cero en reposo",
    "tipo": "Feature",
    "modulo": "GPU (Modal)",
    "prioridad": null,
    "estimacion": null,
    "estado": "Hecho",
    "origen": "Interno",
    "responsable": "Kira Level (dev)",
    "fecha_cierre": "2026-06-17",
    "notas": null
  },
  {
    "id": "PLT-07",
    "fecha_alta": "2026-06-17",
    "creador": "Equipo Eureqa3D",
    "area": "Cortes DICOM",
    "titulo": "Visor de cortes DICOM por caso (NiiVue): cada TAC muestra SUS cortes",
    "historia": "Como cirujano quiero ver los cortes del TAC del propio paciente",
    "tipo": "Feature",
    "modulo": "Visor (NiiVue)",
    "prioridad": null,
    "estimacion": null,
    "estado": "Hecho",
    "origen": "Interno",
    "responsable": "Kira Level (dev)",
    "fecha_cierre": "2026-06-17",
    "notas": null
  },
  {
    "id": "PLT-08",
    "fecha_alta": "2026-06-17",
    "creador": "Equipo Eureqa3D",
    "area": "Casos compartidos",
    "titulo": "Lista de casos compartida en el servidor (GET /api/cases); borrado por caso",
    "historia": "Como equipo quiero que todos veamos los casos subidos, no solo en mi navegador",
    "tipo": "Feature",
    "modulo": "Backend",
    "prioridad": null,
    "estimacion": null,
    "estado": "Hecho",
    "origen": "Interno",
    "responsable": "Kira Level (dev)",
    "fecha_cierre": "2026-06-17",
    "notas": null
  },
  {
    "id": "PLT-09",
    "fecha_alta": "2026-06-17",
    "creador": "Equipo Eureqa3D",
    "area": "Seguridad/RGPD",
    "titulo": "Endpoint GPU con secreto compartido + borrado automatico de casos caducados",
    "historia": "Como responsable quiero proteger el credito GPU y cumplir RGPD",
    "tipo": "Seguridad",
    "modulo": "Backend",
    "prioridad": null,
    "estimacion": null,
    "estado": "Hecho",
    "origen": "Interno",
    "responsable": "Kira Level (dev)",
    "fecha_cierre": "2026-06-17",
    "notas": null
  },
  {
    "id": "PLT-10",
    "fecha_alta": "2026-06-17",
    "creador": "Equipo Eureqa3D",
    "area": "Calibre/estenosis",
    "titulo": "Calibre y estenosis sobre la linea central: radio por punto, linea verde->rojo, punto mas estrecho",
    "historia": "Como cirujano quiero ver el estrechamiento del vaso de forma cuantificada",
    "tipo": "Feature",
    "modulo": "Pipeline + Visor",
    "prioridad": null,
    "estimacion": null,
    "estado": "Hecho",
    "origen": "Interno",
    "responsable": "Kira Level (dev)",
    "fecha_cierre": "2026-06-17",
    "notas": null
  },
  {
    "id": "PLT-11",
    "fecha_alta": "2026-06-17",
    "creador": "Equipo Eureqa3D",
    "area": "Sync 3D<->cortes",
    "titulo": "Cortes embebidos + sincronizacion 3D<->cortes: clic en el 3D mueve el cursor del corte",
    "historia": "Como cirujano quiero correlacionar un punto del 3D con su corte de TAC",
    "tipo": "Feature",
    "modulo": "Visor (NiiVue)",
    "prioridad": null,
    "estimacion": null,
    "estado": "Hecho",
    "origen": "Interno",
    "responsable": "Kira Level (dev)",
    "fecha_cierre": "2026-06-17",
    "notas": null
  },
  {
    "id": "JES-01",
    "fecha_alta": "2026-06-20",
    "creador": "Jesús",
    "area": "Panel derecho",
    "titulo": "Titulo del modelo 3D / TC cargado",
    "historia": "Como cirujano quiero ver el titulo del modelo/TC cargado en la escena para saber que caso estoy viendo",
    "tipo": "Feature",
    "modulo": "Visor (UI)",
    "prioridad": null,
    "estimacion": null,
    "estado": "Hecho",
    "origen": "Jesus #1",
    "responsable": "Kira Level (dev)",
    "fecha_cierre": "2026-06-17",
    "notas": "OK segun Jesus."
  },
  {
    "id": "JES-02",
    "fecha_alta": "2026-06-20",
    "creador": "Jesús",
    "area": "Panel derecho",
    "titulo": "Desplegable de idiomas",
    "historia": "Como usuario quiero cambiar el idioma de la interfaz",
    "tipo": "Feature",
    "modulo": "Visor (i18n)",
    "prioridad": null,
    "estimacion": null,
    "estado": "Hecho",
    "origen": "Jesus #2",
    "responsable": "Kira Level (dev)",
    "fecha_cierre": "2026-06-17",
    "notas": "OK. 5 idiomas ES/EN/FR/DE/IT con banderas."
  },
  {
    "id": "JES-04",
    "fecha_alta": "2026-06-20",
    "creador": "Jesús",
    "area": "Panel derecho",
    "titulo": "Cajones por apartado anatomico con listado de modelos",
    "historia": "Como cirujano quiero los modelos organizados por apartado anatomico",
    "tipo": "Feature",
    "modulo": "Visor (UI)",
    "prioridad": null,
    "estimacion": null,
    "estado": "Hecho",
    "origen": "Jesus #4",
    "responsable": "Kira Level (dev)",
    "fecha_cierre": "2026-06-17",
    "notas": "OK."
  },
  {
    "id": "JES-05",
    "fecha_alta": "2026-06-20",
    "creador": "Jesús",
    "area": "Panel derecho",
    "titulo": "Boton mostrar/ocultar cada cajon completo",
    "historia": "Como cirujano quiero plegar/desplegar un apartado entero",
    "tipo": "Feature",
    "modulo": "Visor (UI)",
    "prioridad": null,
    "estimacion": null,
    "estado": "Hecho",
    "origen": "Jesus #5",
    "responsable": "Kira Level (dev)",
    "fecha_cierre": "2026-06-17",
    "notas": "OK."
  },
  {
    "id": "JES-06",
    "fecha_alta": "2026-06-20",
    "creador": "Jesús",
    "area": "Panel derecho",
    "titulo": "Boton individual mostrar/ocultar cada modelo",
    "historia": "Como cirujano quiero mostrar/ocultar una estructura concreta",
    "tipo": "Feature",
    "modulo": "Visor (UI)",
    "prioridad": null,
    "estimacion": null,
    "estado": "Hecho",
    "origen": "Jesus #6",
    "responsable": "Kira Level (dev)",
    "fecha_cierre": "2026-06-17",
    "notas": "OK."
  },
  {
    "id": "JES-07",
    "fecha_alta": "2026-06-20",
    "creador": "Jesús",
    "area": "Panel derecho",
    "titulo": "Datos por modelo (p.ej. volumen)",
    "historia": "Como cirujano quiero ver datos clinicos de cada estructura (volumen, dimensiones)",
    "tipo": "Feature",
    "modulo": "Visor + Pipeline",
    "prioridad": null,
    "estimacion": null,
    "estado": "Hecho",
    "origen": "Jesus #7",
    "responsable": "Kira Level (dev)",
    "fecha_cierre": "2026-06-17",
    "notas": "OK."
  },
  {
    "id": "JES-09",
    "fecha_alta": "2026-06-20",
    "creador": "Jesús",
    "area": "TC en 3D",
    "titulo": "Barra con los 3 planos de corte del TC",
    "historia": "Como cirujano quiero interactuar con los 3 planos de corte predefinidos del TC",
    "tipo": "Feature",
    "modulo": "Visor (NiiVue)",
    "prioridad": null,
    "estimacion": null,
    "estado": "Hecho",
    "origen": "Jesus #9",
    "responsable": "Kira Level (dev)",
    "fecha_cierre": "2026-06-17",
    "notas": "OK."
  },
  {
    "id": "JES-11",
    "fecha_alta": "2026-06-20",
    "creador": "Jesús",
    "area": "Cortes de seccion",
    "titulo": "Apartado de cortes de seccion con los 3 planos",
    "historia": "Como cirujano quiero cortes de seccion en los 3 planos habituales",
    "tipo": "Feature",
    "modulo": "Visor",
    "prioridad": null,
    "estimacion": null,
    "estado": "Hecho",
    "origen": "Jesus #11",
    "responsable": "Kira Level (dev)",
    "fecha_cierre": "2026-06-17",
    "notas": "OK."
  },
  {
    "id": "JES-13",
    "fecha_alta": "2026-06-20",
    "creador": "Jesús",
    "area": "Herramientas",
    "titulo": "Medir (distancia mm)",
    "historia": "Como cirujano quiero medir distancias en mm sobre el modelo",
    "tipo": "Feature",
    "modulo": "Visor",
    "prioridad": null,
    "estimacion": null,
    "estado": "Hecho",
    "origen": "Jesus #13",
    "responsable": "Kira Level (dev)",
    "fecha_cierre": "2026-06-17",
    "notas": "OK."
  },
  {
    "id": "JES-25",
    "fecha_alta": "2026-06-20",
    "creador": "Jesús",
    "area": "Navegacion",
    "titulo": "Navegacion intravascular (fly-through)",
    "historia": "Como cirujano quiero navegar por el interior de un vaso",
    "tipo": "Feature",
    "modulo": "Visor + Pipeline",
    "prioridad": null,
    "estimacion": null,
    "estado": "Hecho",
    "origen": "Jesus #25",
    "responsable": "Kira Level (dev)",
    "fecha_cierre": "2026-06-17",
    "notas": "OK. Linea central real por esqueletizacion."
  },
  {
    "id": "JES-08",
    "fecha_alta": "2026-06-20",
    "creador": "Jesús",
    "area": "TC en 3D",
    "titulo": "Renombrar TAC -> TC (terminologia)",
    "historia": "Como cirujano quiero la nomenclatura correcta: TC (no TAC, obsoleto desde el multicorte)",
    "tipo": "Mejora",
    "modulo": "Visor (UI + i18n)",
    "prioridad": "Alta",
    "estimacion": "S",
    "estado": "Pendiente",
    "origen": "Jesus #8",
    "responsable": "Kira Level (dev)",
    "fecha_cierre": null,
    "notas": "QUICK WIN. Jesus: 'TAC' es nomenclatura antigua (Tomografia Axial Computarizada); hoy son multicorte. Renombrar en TODOS los textos e idiomas, incl. memoria/docs internas."
  },
  {
    "id": "JES-10",
    "fecha_alta": "2026-06-20",
    "creador": "Jesús",
    "area": "TC en 3D",
    "titulo": "Selector de flechas para avanzar/retroceder cortes de 1 en 1 (TC)",
    "historia": "Como cirujano quiero avanzar/retroceder corte a corte (1 en 1) para buscar la correlacion TC<->3D en puntos criticos",
    "tipo": "Feature",
    "modulo": "Visor (NiiVue)",
    "prioridad": "Alta",
    "estimacion": "M",
    "estado": "Pendiente",
    "origen": "Jesus #10",
    "responsable": "Kira Level (dev)",
    "fecha_cierre": null,
    "notas": "Jesus: los cirujanos se mueven 5-10 cortes buscando 'sentido anatomico' o descartando artefactos. Flechas a izquierda dada la disposicion de la barra. Mostrar indice de corte actual."
  },
  {
    "id": "JES-14",
    "fecha_alta": "2026-06-20",
    "creador": "Jesús",
    "area": "Mediciones",
    "titulo": "Mediciones registradas: guardar con nombre + recuadro + toggle puntos amarillos",
    "historia": "Como cirujano quiero guardar una medicion con nombre, verla en un recuadro y poder ocultar los puntos amarillos",
    "tipo": "Feature",
    "modulo": "Visor + Backend",
    "prioridad": "Alta",
    "estimacion": "L",
    "estado": "Pendiente",
    "origen": "Jesus #14",
    "responsable": "Kira Level (dev)",
    "fecha_cierre": null,
    "notas": "Poner NOMBRE a cada medicion (importante segun Jesus). Toggle de puntos extremos (menos importante). Base de #15/#16."
  },
  {
    "id": "JES-15",
    "fecha_alta": "2026-06-20",
    "creador": "Jesús",
    "area": "Mediciones",
    "titulo": "Persistencia y comparticion de mediciones por enlace",
    "historia": "Como cirujano quiero que mis mediciones queden guardadas en el modelo y sigan visibles si comparto el enlace con otro cirujano",
    "tipo": "Feature",
    "modulo": "Backend (persistencia)",
    "prioridad": "Alta",
    "estimacion": "L",
    "estado": "Pendiente",
    "origen": "Jesus #15",
    "responsable": "Kira Level (dev)",
    "fecha_cierre": null,
    "notas": "Requiere guardar anotaciones por caso en servidor (no solo en navegador). Depende de #14."
  },
  {
    "id": "JES-17",
    "fecha_alta": "2026-06-20",
    "creador": "Jesús",
    "area": "Anotaciones",
    "titulo": "Puntos/marcadores sobre superficie + cuadro de texto flotante editable",
    "historia": "Como cirujano quiero colocar puntos/simbolos sobre una coordenada de la superficie con un cuadro de texto editable que se muestra/oculta al seleccionar el punto",
    "tipo": "Feature",
    "modulo": "Visor + Backend",
    "prioridad": "Alta",
    "estimacion": "L",
    "estado": "Pendiente",
    "origen": "Jesus #17",
    "responsable": "Kira Level (dev)",
    "fecha_cierre": null,
    "notas": "Markers anclados a coordenada de superficie. Texto flotante editable. Toggle por seleccion. Funcionalidad nueva grande, muy pedida."
  },
  {
    "id": "JES-24",
    "fecha_alta": "2026-06-20",
    "creador": "Jesús",
    "area": "Vistas guardadas",
    "titulo": "Vistas guardadas tipo Sketchfab (camara + zoom + elementos anclados)",
    "historia": "Como cirujano quiero guardar una 'vista' (angulo de camara, zoom, puntos/textos/mediciones y corte) y volver a ella desde un listado",
    "tipo": "Feature",
    "modulo": "Visor + Backend",
    "prioridad": "Alta",
    "estimacion": "XL",
    "estado": "Backlog",
    "origen": "Jesus #24",
    "responsable": "Kira Level (dev)",
    "fecha_cierre": null,
    "notas": "DIFERENCIADOR. Referencia: Sketchfab. La camara viaja al angulo/zoom guardado y muestra los elementos anclados. Alto valor, esfuerzo alto."
  },
  {
    "id": "JES-26",
    "fecha_alta": "2026-06-20",
    "creador": "Jesús",
    "area": "Mediciones",
    "titulo": "Anotacion explicativa en 'distancia entre 2 estructuras'",
    "historia": "Como cirujano quiero un texto que explique que la herramienta calcula la distancia mas corta entre 2 estructuras e indica los puntos de medicion",
    "tipo": "Mejora",
    "modulo": "Visor (UI)",
    "prioridad": "Alta",
    "estimacion": "S",
    "estado": "En curso",
    "origen": "Jesus #26",
    "responsable": "Kira Level (dev)",
    "fecha_cierre": null,
    "notas": "QUICK WIN. Jesus: sin la anotacion la herramienta no se entiende; con ella permite decisiones dicotomicas rapidas (p.ej. <5mm del tumor -> extirpo). Texto al pie del recuadro."
  },
  {
    "id": "PRD-02",
    "fecha_alta": "2026-06-20",
    "creador": "Equipo Eureqa3D",
    "area": "Plataforma / Estrategico",
    "titulo": "Caso real de Jesus (TAC abdominal) por IA en GPU -> modelo del paciente",
    "historia": "Como Eureqa3D quiero procesar un caso real de Jesus de extremo a extremo",
    "tipo": "Feature",
    "modulo": "GPU + Pipeline",
    "prioridad": "Alta",
    "estimacion": "M",
    "estado": "Pendiente",
    "origen": "Interno",
    "responsable": "Equipo Eureqa3D",
    "fecha_cierre": null,
    "notas": null
  },
  {
    "id": "PRD-06",
    "fecha_alta": "2026-06-20",
    "creador": "Equipo Eureqa3D",
    "area": "Plataforma / Estrategico",
    "titulo": "Validacion por radiologo de la auto-segmentacion",
    "historia": "Como cliente quiero que un radiologo valide la segmentacion antes de usarla",
    "tipo": "Estrategico",
    "modulo": "Proceso",
    "prioridad": "Alta",
    "estimacion": "L",
    "estado": "Backlog",
    "origen": "Estrategico",
    "responsable": "Equipo Eureqa3D",
    "fecha_cierre": null,
    "notas": null
  },
  {
    "id": "PRD-07",
    "fecha_alta": "2026-06-20",
    "creador": "Antonio",
    "area": "Plataforma / Estrategico",
    "titulo": "Marcado CE (ISO 13485 / MDR)",
    "historia": "Como empresa quiero el marcado CE para poder vender a hospitales",
    "tipo": "Estrategico",
    "modulo": "Regulatorio",
    "prioridad": "Alta",
    "estimacion": "XL",
    "estado": "Backlog",
    "origen": "Estrategico",
    "responsable": "Antonio",
    "fecha_cierre": null,
    "notas": null
  },
  {
    "id": "JES-12",
    "fecha_alta": "2026-06-20",
    "creador": "Jesús",
    "area": "Cortes de seccion",
    "titulo": "Flechas +-1 tambien en cortes de seccion",
    "historia": "Como cirujano quiero avanzar corte a corte tambien en los cortes de seccion",
    "tipo": "Feature",
    "modulo": "Visor",
    "prioridad": "Baja",
    "estimacion": "S",
    "estado": "Backlog",
    "origen": "Jesus #12",
    "responsable": "Kira Level (dev)",
    "fecha_cierre": null,
    "notas": "Jesus: 'quizas aqui no aporta tanto'. Reutiliza el control de #10. Baja prioridad."
  },
  {
    "id": "JES-28",
    "fecha_alta": "2026-06-20",
    "creador": "Jesús",
    "area": "Orientacion",
    "titulo": "Renombrar 'centrar imagen' -> 'volver a vista inicial'",
    "historia": "Como cirujano quiero que el boton se llame 'volver a vista inicial' para entender que hace",
    "tipo": "Mejora",
    "modulo": "Visor (UI)",
    "prioridad": "Baja",
    "estimacion": "S",
    "estado": "Pendiente",
    "origen": "Jesus #28",
    "responsable": "Kira Level (dev)",
    "fecha_cierre": null,
    "notas": "QUICK WIN. Se puede integrar en el ViewCube #27."
  },
  {
    "id": "CEL-02",
    "fecha_alta": "2026-06-20",
    "creador": "Equipo Eureqa3D",
    "area": "Cella (competencia)",
    "titulo": "Simulacion de clampaje vascular -> volumen isquemico vs remanente",
    "historia": "Como cirujano quiero simular el clampaje y ver el volumen isquemico (nefrectomia parcial)",
    "tipo": "Feature",
    "modulo": "Visor + Pipeline",
    "prioridad": "Baja",
    "estimacion": "XL",
    "estado": "Backlog",
    "origen": "Cella",
    "responsable": "Kira Level (dev)",
    "fecha_cierre": null,
    "notas": "Inspirado en la suite de planificacion quirurgica de Cella."
  },
  {
    "id": "CEL-05",
    "fecha_alta": "2026-06-20",
    "creador": "Equipo Eureqa3D",
    "area": "Cella (competencia)",
    "titulo": "Etiquetado clinico rico validado por radiologo (arterial/venoso/portal, adenopatias, etc.)",
    "historia": "Como cirujano quiero estructuras etiquetadas y validadas por radiologo",
    "tipo": "Feature",
    "modulo": "Pipeline + revision",
    "prioridad": "Baja",
    "estimacion": "XL",
    "estado": "Backlog",
    "origen": "Cella",
    "responsable": "Kira Level (dev)",
    "fecha_cierre": null,
    "notas": "Inspirado en la suite de planificacion quirurgica de Cella."
  },
  {
    "id": "PRD-09",
    "fecha_alta": "2026-06-20",
    "creador": "Kira Level (dev)",
    "area": "Plataforma / Estrategico",
    "titulo": "RV inmersiva (WebXR) + AR de sobremesa en movil (model-viewer)",
    "historia": "Como cirujano quiero ver el modelo en gafas o en AR sobre la mesa",
    "tipo": "Feature",
    "modulo": "Visor (XR)",
    "prioridad": "Baja",
    "estimacion": "XL",
    "estado": "Backlog",
    "origen": "Interno",
    "responsable": "Kira Level (dev)",
    "fecha_cierre": null,
    "notas": null
  },
  {
    "id": "JES-03",
    "fecha_alta": "2026-06-20",
    "creador": "Jesús",
    "area": "Panel derecho",
    "titulo": "Botones encender/apagar agrupaciones de modelos 3D",
    "historia": "Como cirujano quiero encender/apagar grupos de estructuras de una vez",
    "tipo": "Mejora",
    "modulo": "Visor (UI)",
    "prioridad": "Media",
    "estimacion": "S",
    "estado": "Duda",
    "origen": "Jesus #3",
    "responsable": "Kira Level (dev)",
    "fecha_cierre": null,
    "notas": "Jesus marca DUDA. Hoy existen presets/agrupacion por categoria. ACLARAR con Jesus que comportamiento exacto espera (toggle por grupo vs preset)."
  },
  {
    "id": "JES-16",
    "fecha_alta": "2026-06-20",
    "creador": "Jesús",
    "area": "Mediciones",
    "titulo": "Mediciones creadas por Eureqa3D (autoria) y guardadas",
    "historia": "Como Eureqa3D quiero dejar mediciones ya hechas y guardadas antes de enviar el modelo al cirujano",
    "tipo": "Feature",
    "modulo": "Backend + Visor",
    "prioridad": "Media",
    "estimacion": "M",
    "estado": "Backlog",
    "origen": "Jesus #16",
    "responsable": "Kira Level (dev)",
    "fecha_cierre": null,
    "notas": "Autoria 'Eureqa3D'. Depende de #15. Relacionado con roles #21."
  },
  {
    "id": "JES-19",
    "fecha_alta": "2026-06-20",
    "creador": "Jesús",
    "area": "Anotaciones",
    "titulo": "Listado de puntos guardados con su texto y nombre",
    "historia": "Como cirujano quiero un cuadro con el listado de puntos creados, cada uno con su nombre",
    "tipo": "Feature",
    "modulo": "Visor (UI)",
    "prioridad": "Media",
    "estimacion": "M",
    "estado": "Pendiente",
    "origen": "Jesus #19",
    "responsable": "Kira Level (dev)",
    "fecha_cierre": null,
    "notas": "(Jesus salta el #18). Parte de la misma epica que #17."
  },
  {
    "id": "JES-20",
    "fecha_alta": "2026-06-20",
    "creador": "Jesús",
    "area": "Anotaciones",
    "titulo": "Puntos compartibles + autoria Eureqa3D + el cirujano anade despues",
    "historia": "Como cirujano quiero que los puntos se guarden y compartan como las mediciones; que Eureqa3D los anada antes de enviar y yo pueda anadir los mios despues",
    "tipo": "Feature",
    "modulo": "Backend + Visor",
    "prioridad": "Media",
    "estimacion": "L",
    "estado": "Backlog",
    "origen": "Jesus #20",
    "responsable": "Kira Level (dev)",
    "fecha_cierre": null,
    "notas": "Misma persistencia que #15. Autoria mixta Eureqa3D + cirujano."
  },
  {
    "id": "JES-21",
    "fecha_alta": "2026-06-20",
    "creador": "Jesús",
    "area": "Permisos/Roles",
    "titulo": "Elementos de Eureqa3D no editables/borrables por el cirujano (solo mostrar/ocultar)",
    "historia": "Como Eureqa3D quiero que mis mediciones/puntos no puedan ser borrados ni editados por el cirujano, solo mostrados/ocultados",
    "tipo": "Feature",
    "modulo": "Backend (roles)",
    "prioridad": "Media",
    "estimacion": "L",
    "estado": "Backlog",
    "origen": "Jesus #21",
    "responsable": "Kira Level (dev)",
    "fecha_cierre": null,
    "notas": "Requiere modelo de roles/propiedad de anotaciones. Transversal a #15/#16/#20."
  },
  {
    "id": "JES-22",
    "fecha_alta": "2026-06-20",
    "creador": "Jesús",
    "area": "Capturas",
    "titulo": "Captura de pantalla de la escena (corte + punto + medicion)",
    "historia": "Como cirujano quiero capturar un pantallazo de la escena con el corte ajustado, un punto y/o una medicion visibles",
    "tipo": "Feature",
    "modulo": "Visor",
    "prioridad": "Media",
    "estimacion": "M",
    "estado": "Pendiente",
    "origen": "Jesus #22",
    "responsable": "Kira Level (dev)",
    "fecha_cierre": null,
    "notas": "Render de la escena actual a imagen."
  },
  {
    "id": "JES-23",
    "fecha_alta": "2026-06-20",
    "creador": "Jesús",
    "area": "Capturas",
    "titulo": "Galeria de pantallazos guardados (abrir en pestana / descargar, sin invadir la escena)",
    "historia": "Como cirujano quiero un anexo con el listado de pantallazos para abrir en otra pestana o descargar, sin que invadan la escena 3D",
    "tipo": "Feature",
    "modulo": "Visor + Backend",
    "prioridad": "Media",
    "estimacion": "M",
    "estado": "Pendiente",
    "origen": "Jesus #23",
    "responsable": "Kira Level (dev)",
    "fecha_cierre": null,
    "notas": "Depende de #22. Guardado por caso."
  },
  {
    "id": "JES-27",
    "fecha_alta": "2026-06-20",
    "creador": "Jesús",
    "area": "Orientacion",
    "titulo": "ViewCube interactivo tipo Fusion 360 (esquina sup. derecha) + 'volver al inicio'",
    "historia": "Como cirujano quiero un cubo de orientacion interactivo que recoloque la camara al clicar una cara, util si me pierdo navegando",
    "tipo": "Feature",
    "modulo": "Visor",
    "prioridad": "Media",
    "estimacion": "M",
    "estado": "Pendiente",
    "origen": "Jesus #27",
    "responsable": "Kira Level (dev)",
    "fecha_cierre": null,
    "notas": "Incluir 'volver a vista inicial' (fusiona con #28). Tambien pedido en ideas de Cella (muneco de orientacion)."
  },
  {
    "id": "CEL-01",
    "fecha_alta": "2026-06-20",
    "creador": "Equipo Eureqa3D",
    "area": "Cella (competencia)",
    "titulo": "Volumetria por segmentos (Couinaud hepatico, pulmonar, renal) + volumen remanente",
    "historia": "Como cirujano quiero volumen por segmento y volumen remanente para planificar resecciones",
    "tipo": "Feature",
    "modulo": "Visor + Pipeline",
    "prioridad": "Media",
    "estimacion": "L",
    "estado": "Backlog",
    "origen": "Cella",
    "responsable": "Kira Level (dev)",
    "fecha_cierre": null,
    "notas": "Inspirado en la suite de planificacion quirurgica de Cella."
  },
  {
    "id": "CEL-03",
    "fecha_alta": "2026-06-20",
    "creador": "Equipo Eureqa3D",
    "area": "Cella (competencia)",
    "titulo": "Margenes de seguridad de reseccion (5/10 mm) sobre el tumor",
    "historia": "Como cirujano quiero ver margenes de 5/10 mm alrededor del tumor, visual y cuantificado",
    "tipo": "Feature",
    "modulo": "Visor + Pipeline",
    "prioridad": "Media",
    "estimacion": "L",
    "estado": "Backlog",
    "origen": "Cella",
    "responsable": "Kira Level (dev)",
    "fecha_cierre": null,
    "notas": "Inspirado en la suite de planificacion quirurgica de Cella."
  },
  {
    "id": "CEL-04",
    "fecha_alta": "2026-06-20",
    "creador": "Equipo Eureqa3D",
    "area": "Cella (competencia)",
    "titulo": "Contacto/infiltracion tumor<->estructuras (que toca y cuanto)",
    "historia": "Como cirujano quiero saber que organos/vasos toca el tumor y en que grado",
    "tipo": "Feature",
    "modulo": "Visor + Pipeline",
    "prioridad": "Media",
    "estimacion": "L",
    "estado": "Backlog",
    "origen": "Cella",
    "responsable": "Kira Level (dev)",
    "fecha_cierre": null,
    "notas": "Inspirado en la suite de planificacion quirurgica de Cella."
  },
  {
    "id": "CEL-06",
    "fecha_alta": "2026-06-20",
    "creador": "Equipo Eureqa3D",
    "area": "Cella (competencia)",
    "titulo": "Exportar a Excel/informe de volumenes y mediciones",
    "historia": "Como cirujano quiero exportar volumenes y mediciones a un informe",
    "tipo": "Feature",
    "modulo": "Backend",
    "prioridad": "Media",
    "estimacion": "M",
    "estado": "Backlog",
    "origen": "Cella",
    "responsable": "Kira Level (dev)",
    "fecha_cierre": null,
    "notas": "Inspirado en la suite de planificacion quirurgica de Cella."
  },
  {
    "id": "PRD-01",
    "fecha_alta": "2026-06-20",
    "creador": "Equipo Eureqa3D",
    "area": "Plataforma / Estrategico",
    "titulo": "Resaltar la estructura clicada al sincronizar cortes<->3D",
    "historia": "Como cirujano quiero que al clicar se resalte la estructura, no solo mover el cursor del corte",
    "tipo": "Feature",
    "modulo": "Visor",
    "prioridad": "Media",
    "estimacion": "M",
    "estado": "Pendiente",
    "origen": "Interno",
    "responsable": "Equipo Eureqa3D",
    "fecha_cierre": null,
    "notas": null
  },
  {
    "id": "PRD-03",
    "fecha_alta": "2026-06-20",
    "creador": "Equipo Eureqa3D",
    "area": "Plataforma / Estrategico",
    "titulo": "Gestion de casos multiusuario (login + lista por usuario)",
    "historia": "Como usuario quiero ver solo mis casos tras iniciar sesion",
    "tipo": "Feature",
    "modulo": "Backend (auth)",
    "prioridad": "Media",
    "estimacion": "L",
    "estado": "Backlog",
    "origen": "Interno",
    "responsable": "Equipo Eureqa3D",
    "fecha_cierre": null,
    "notas": null
  },
  {
    "id": "PRD-04",
    "fecha_alta": "2026-06-20",
    "creador": "Kira Level (dev)",
    "area": "Plataforma / Estrategico",
    "titulo": "Optimizar deploy de Railway (imagen minima, deploys <1 min)",
    "historia": "Como dev quiero deploys rapidos sacando el procesado pesado de la imagen",
    "tipo": "Feature",
    "modulo": "Infra",
    "prioridad": "Media",
    "estimacion": "M",
    "estado": "Backlog",
    "origen": "Interno",
    "responsable": "Kira Level (dev)",
    "fecha_cierre": null,
    "notas": null
  },
  {
    "id": "PRD-05",
    "fecha_alta": "2026-06-20",
    "creador": "Kira Level (dev)",
    "area": "Plataforma / Estrategico",
    "titulo": "Rediseno UI/UX moderno del visor (tipografia, espaciados, paneles)",
    "historia": "Como usuario quiero una interfaz mas moderna y coherente con la marca",
    "tipo": "Feature",
    "modulo": "Visor (UI)",
    "prioridad": "Media",
    "estimacion": "L",
    "estado": "Backlog",
    "origen": "Interno",
    "responsable": "Kira Level (dev)",
    "fecha_cierre": null,
    "notas": null
  },
  {
    "id": "PRD-08",
    "fecha_alta": "2026-06-20",
    "creador": "Antonio",
    "area": "Plataforma / Estrategico",
    "titulo": "Agente que vigile licitaciones publicas a nivel nacional",
    "historia": "Como empresa quiero un agente que vigile a nivel nacional las licitaciones a las que podamos optar (PLACSP/BOE), filtre por sector salud/3D y nos avise",
    "tipo": "Feature",
    "modulo": "Ops / Negocio",
    "prioridad": "Media",
    "estimacion": "M",
    "estado": "Backlog",
    "origen": "Antonio",
    "responsable": "Antonio",
    "fecha_cierre": null,
    "notas": null
  },
  {
    "id": "PRD-10",
    "fecha_alta": "2026-06-20",
    "creador": "Antonio",
    "area": "IA / Diferenciación",
    "titulo": "Tutor AI contextual — clic en órgano → asistente responde en contexto",
    "historia": "Como cirujano quiero clicar sobre una estructura del modelo 3D y preguntarle al asistente sobre ella, recibiendo respuestas contextuales (nombre, función, relaciones anatómicas, implicaciones quirúrgicas) sin salir del visor",
    "tipo": "Feature",
    "modulo": "Visor (Three.js raycasting) + API Anthropic",
    "prioridad": "Alta",
    "estimacion": "XL",
    "estado": "Backlog",
    "origen": "Interno",
    "responsable": "Kira Level (dev)",
    "fecha_cierre": null,
    "notas": "DIFERENCIADOR MUNDIAL. Ningún competidor analizado (Cella, BioDigital, 3D Organon, Visible Body, Mimics, Anatomage) tiene esta funcionalidad. Enatom la está desarrollando solo para educación. Implementación: raycasting Three.js identifica la malla clicada → obtiene nombre del segmento + metadatos (volumen, categoría) → construye prompt contextual → llama a Anthropic SDK (claude-sonnet-4-6) → respuesta en panel lateral del visor. El contexto puede enriquecerse con el caso clínico (tipo de cirugía, estructuras vecinas visibles, mediciones activas). Fase 2: el asistente puede responder sobre lo que está visible en pantalla (frustum culling) no solo lo clicado. Fase 3: modo dictado — el cirujano habla y el asistente anota observaciones sobre el modelo."
  }
];

module.exports = SEED;
